/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Address = IDL.Record({
  'id' : IDL.Text,
  'street' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'postalCode' : IDL.Text,
  'state' : IDL.Text,
  'isPrimary' : IDL.Bool,
  'addressLabel' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'customerId' : IDL.Text,
});
export const Customer = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
});
export const Time = IDL.Int;
export const Invoice = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'dateIssued' : Time,
  'dueDate' : Time,
  'timeEntryIds' : IDL.Vec(IDL.Text),
  'jobIds' : IDL.Vec(IDL.Text),
  'materialEntryIds' : IDL.Vec(IDL.Text),
  'totalAmount' : IDL.Float64,
  'notes' : IDL.Opt(IDL.Text),
  'timeBlockIds' : IDL.Vec(IDL.Text),
  'customerId' : IDL.Text,
});
export const Job = IDL.Record({
  'id' : IDL.Text,
  'startTime' : Time,
  'status' : IDL.Text,
  'endTime' : Time,
  'cost' : IDL.Float64,
  'isActive' : IDL.Bool,
  'addressId' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'customerId' : IDL.Text,
  'serviceId' : IDL.Text,
});
export const Service = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'notes' : IDL.Opt(IDL.Text),
  'price' : IDL.Float64,
  'laborRate' : IDL.Float64,
});
export const Visit = IDL.Record({
  'id' : IDL.Text,
  'startTime' : IDL.Opt(Time),
  'status' : IDL.Text,
  'endTime' : IDL.Opt(Time),
  'scheduledDate' : Time,
  'createdAt' : Time,
  'laborHours' : IDL.Float64,
  'jobId' : IDL.Text,
  'photoIds' : IDL.Vec(IDL.Text),
  'updatedAt' : Time,
  'notes' : IDL.Opt(IDL.Text),
  'internalNotes' : IDL.Opt(IDL.Text),
  'laborCost' : IDL.Float64,
  'laborRate' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const Settings = IDL.Record({
  'invoiceStartingNumber' : IDL.Nat,
  'paymentTermsDays' : IDL.Nat,
  'defaultTaxRate' : IDL.Float64,
  'companyEmail' : IDL.Text,
  'invoicePrefix' : IDL.Text,
  'defaultLaborRate' : IDL.Float64,
  'currency' : IDL.Text,
  'companyName' : IDL.Text,
  'companyPhone' : IDL.Text,
  'companyAddress' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAddress' : IDL.Func([Address], [], []),
  'addCustomer' : IDL.Func([Customer], [], []),
  'addInvoice' : IDL.Func([Invoice], [], []),
  'addJob' : IDL.Func([Job], [], []),
  'addService' : IDL.Func([Service], [], []),
  'addVisit' : IDL.Func([Visit], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getActiveAddressesByCustomer' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Address)],
      ['query'],
    ),
  'getAddress' : IDL.Func([IDL.Text], [IDL.Opt(Address)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([IDL.Text], [IDL.Opt(Customer)], ['query']),
  'getInvoicesByCustomer' : IDL.Func([IDL.Text], [IDL.Vec(Invoice)], ['query']),
  'getJob' : IDL.Func([IDL.Text], [IDL.Opt(Job)], ['query']),
  'getJobServices' : IDL.Func([IDL.Text], [IDL.Vec(Service)], ['query']),
  'getJobsByAddress' : IDL.Func([IDL.Text], [IDL.Vec(Job)], ['query']),
  'getSettings' : IDL.Func([], [Settings], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVisit' : IDL.Func([IDL.Text], [IDL.Opt(Visit)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listActiveCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'listAddressesByCustomer' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Address)],
      ['query'],
    ),
  'listVisitsByJob' : IDL.Func([IDL.Text], [IDL.Vec(Visit)], ['query']),
  'loadSeedData' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateJob' : IDL.Func([Job], [], []),
  'updateSettings' : IDL.Func([Settings], [], []),
  'updateVisit' : IDL.Func([Visit], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Address = IDL.Record({
    'id' : IDL.Text,
    'street' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'postalCode' : IDL.Text,
    'state' : IDL.Text,
    'isPrimary' : IDL.Bool,
    'addressLabel' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'customerId' : IDL.Text,
  });
  const Customer = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
  });
  const Time = IDL.Int;
  const Invoice = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'dateIssued' : Time,
    'dueDate' : Time,
    'timeEntryIds' : IDL.Vec(IDL.Text),
    'jobIds' : IDL.Vec(IDL.Text),
    'materialEntryIds' : IDL.Vec(IDL.Text),
    'totalAmount' : IDL.Float64,
    'notes' : IDL.Opt(IDL.Text),
    'timeBlockIds' : IDL.Vec(IDL.Text),
    'customerId' : IDL.Text,
  });
  const Job = IDL.Record({
    'id' : IDL.Text,
    'startTime' : Time,
    'status' : IDL.Text,
    'endTime' : Time,
    'cost' : IDL.Float64,
    'isActive' : IDL.Bool,
    'addressId' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'customerId' : IDL.Text,
    'serviceId' : IDL.Text,
  });
  const Service = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'notes' : IDL.Opt(IDL.Text),
    'price' : IDL.Float64,
    'laborRate' : IDL.Float64,
  });
  const Visit = IDL.Record({
    'id' : IDL.Text,
    'startTime' : IDL.Opt(Time),
    'status' : IDL.Text,
    'endTime' : IDL.Opt(Time),
    'scheduledDate' : Time,
    'createdAt' : Time,
    'laborHours' : IDL.Float64,
    'jobId' : IDL.Text,
    'photoIds' : IDL.Vec(IDL.Text),
    'updatedAt' : Time,
    'notes' : IDL.Opt(IDL.Text),
    'internalNotes' : IDL.Opt(IDL.Text),
    'laborCost' : IDL.Float64,
    'laborRate' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Settings = IDL.Record({
    'invoiceStartingNumber' : IDL.Nat,
    'paymentTermsDays' : IDL.Nat,
    'defaultTaxRate' : IDL.Float64,
    'companyEmail' : IDL.Text,
    'invoicePrefix' : IDL.Text,
    'defaultLaborRate' : IDL.Float64,
    'currency' : IDL.Text,
    'companyName' : IDL.Text,
    'companyPhone' : IDL.Text,
    'companyAddress' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAddress' : IDL.Func([Address], [], []),
    'addCustomer' : IDL.Func([Customer], [], []),
    'addInvoice' : IDL.Func([Invoice], [], []),
    'addJob' : IDL.Func([Job], [], []),
    'addService' : IDL.Func([Service], [], []),
    'addVisit' : IDL.Func([Visit], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getActiveAddressesByCustomer' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Address)],
        ['query'],
      ),
    'getAddress' : IDL.Func([IDL.Text], [IDL.Opt(Address)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([IDL.Text], [IDL.Opt(Customer)], ['query']),
    'getInvoicesByCustomer' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Invoice)],
        ['query'],
      ),
    'getJob' : IDL.Func([IDL.Text], [IDL.Opt(Job)], ['query']),
    'getJobServices' : IDL.Func([IDL.Text], [IDL.Vec(Service)], ['query']),
    'getJobsByAddress' : IDL.Func([IDL.Text], [IDL.Vec(Job)], ['query']),
    'getSettings' : IDL.Func([], [Settings], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVisit' : IDL.Func([IDL.Text], [IDL.Opt(Visit)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listActiveCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'listAddressesByCustomer' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Address)],
        ['query'],
      ),
    'listVisitsByJob' : IDL.Func([IDL.Text], [IDL.Vec(Visit)], ['query']),
    'loadSeedData' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateJob' : IDL.Func([Job], [], []),
    'updateSettings' : IDL.Func([Settings], [], []),
    'updateVisit' : IDL.Func([Visit], [], []),
  });
};

export const init = ({ IDL }) => { return []; };