/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'id' : string,
  'street' : string,
  'country' : string,
  'city' : string,
  'postalCode' : string,
  'state' : string,
  'isPrimary' : boolean,
  'addressLabel' : string,
  'notes' : [] | [string],
  'customerId' : string,
}
export interface Customer {
  'id' : string,
  'name' : string,
  'tags' : Array<string>,
  'isActive' : boolean,
  'email' : string,
  'notes' : [] | [string],
  'phone' : string,
}
export interface Invoice {
  'id' : string,
  'status' : string,
  'dateIssued' : Time,
  'dueDate' : Time,
  'timeEntryIds' : Array<string>,
  'jobIds' : Array<string>,
  'materialEntryIds' : Array<string>,
  'totalAmount' : number,
  'notes' : [] | [string],
  'timeBlockIds' : Array<string>,
  'customerId' : string,
}
export interface Job {
  'id' : string,
  'startTime' : Time,
  'status' : string,
  'endTime' : Time,
  'cost' : number,
  'isActive' : boolean,
  'addressId' : string,
  'notes' : [] | [string],
  'customerId' : string,
  'serviceId' : string,
}
export interface Service {
  'id' : string,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'notes' : [] | [string],
  'price' : number,
  'laborRate' : number,
}
export interface Settings {
  'invoiceStartingNumber' : bigint,
  'paymentTermsDays' : bigint,
  'defaultTaxRate' : number,
  'companyEmail' : string,
  'invoicePrefix' : string,
  'defaultLaborRate' : number,
  'currency' : string,
  'companyName' : string,
  'companyPhone' : string,
  'companyAddress' : string,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : string,
  'isActive' : boolean,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAddress' : ActorMethod<[Address], undefined>,
  'addCustomer' : ActorMethod<[Customer], undefined>,
  'addInvoice' : ActorMethod<[Invoice], undefined>,
  'addJob' : ActorMethod<[Job], undefined>,
  'addService' : ActorMethod<[Service], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getActiveAddressesByCustomer' : ActorMethod<[string], Array<Address>>,
  'getAddress' : ActorMethod<[string], [] | [Address]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomer' : ActorMethod<[string], [] | [Customer]>,
  'getInvoicesByCustomer' : ActorMethod<[string], Array<Invoice>>,
  'getJob' : ActorMethod<[string], [] | [Job]>,
  'getJobServices' : ActorMethod<[string], Array<Service>>,
  'getJobsByAddress' : ActorMethod<[string], Array<Job>>,
  'getSettings' : ActorMethod<[], Settings>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listActiveCustomers' : ActorMethod<[], Array<Customer>>,
  'listAddressesByCustomer' : ActorMethod<[string], Array<Address>>,
  'loadSeedData' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateSettings' : ActorMethod<[Settings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];