/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Service {
    id: string;
    name: string;
    description: string;
    isActive: boolean;
    notes?: string;
    price: number;
    laborRate: number;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Expense {
    id: string;
    expenseType: string;
    dateIncurred: Time;
    jobId?: string;
    description: string;
    notes?: string;
    visitId?: string;
    amount: number;
    vendorName?: string;
    receiptBlobId?: string;
}
export interface Customer {
    id: string;
    name: string;
    tags: Array<string>;
    isActive: boolean;
    email: string;
    notes?: string;
    phone: string;
}
export interface Invoice {
    id: string;
    status: string;
    dateIssued: Time;
    dueDate: Time;
    timeEntryIds: Array<string>;
    jobIds: Array<string>;
    materialEntryIds: Array<string>;
    totalAmount: number;
    notes?: string;
    timeBlockIds: Array<string>;
    customerId: string;
}
export interface Settings {
    invoiceStartingNumber: bigint;
    paymentTermsDays: bigint;
    defaultTaxRate: number;
    companyEmail: string;
    invoicePrefix: string;
    defaultLaborRate: number;
    currency: string;
    companyName: string;
    companyPhone: string;
    companyAddress: string;
}
export interface Job {
    id: string;
    startTime: Time;
    status: string;
    endTime: Time;
    cost: number;
    isActive: boolean;
    addressId: string;
    notes?: string;
    customerId: string;
    serviceId: string;
}
export interface Visit {
    id: string;
    startTime?: Time;
    status: string;
    endTime?: Time;
    scheduledDate: Time;
    createdAt: Time;
    laborHours: number;
    jobId: string;
    photoIds: Array<string>;
    updatedAt: Time;
    notes?: string;
    internalNotes?: string;
    laborCost: number;
    laborRate: number;
}
export interface UserProfile {
    name: string;
    role: string;
    isActive: boolean;
    email: string;
    phone: string;
}
export interface Address {
    id: string;
    street: string;
    country: string;
    city: string;
    postalCode: string;
    state: string;
    isPrimary: boolean;
    addressLabel: string;
    notes?: string;
    customerId: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAddress(address: Address): Promise<void>;
    addCustomer(customer: Customer): Promise<void>;
    addExpense(expense: Expense): Promise<void>;
    addInvoice(invoice: Invoice): Promise<void>;
    addJob(job: Job): Promise<void>;
    addService(service: Service): Promise<void>;
    addVisit(visit: Visit): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteExpense(id: string): Promise<void>;
    getActiveAddressesByCustomer(customerId: string): Promise<Array<Address>>;
    getAddress(id: string): Promise<Address | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomer(id: string): Promise<Customer | null>;
    getInvoicesByCustomer(customerId: string): Promise<Array<Invoice>>;
    getJob(id: string): Promise<Job | null>;
    getJobServices(jobId: string): Promise<Array<Service>>;
    getJobsByAddress(addressId: string): Promise<Array<Job>>;
    getSettings(): Promise<Settings>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVisit(id: string): Promise<Visit | null>;
    isCallerAdmin(): Promise<boolean>;
    listActiveCustomers(): Promise<Array<Customer>>;
    listAddressesByCustomer(customerId: string): Promise<Array<Address>>;
    listAllExpenses(): Promise<Array<Expense>>;
    listExpensesByJob(jobId: string): Promise<Array<Expense>>;
    listExpensesByVisit(visitId: string): Promise<Array<Expense>>;
    listVisitsByJob(jobId: string): Promise<Array<Visit>>;
    loadSeedData(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateExpense(expense: Expense): Promise<void>;
    updateJob(job: Job): Promise<void>;
    updateSettings(newSettings: Settings): Promise<void>;
    updateVisit(visit: Visit): Promise<void>;
}
import type { Address as _Address, Customer as _Customer, Expense as _Expense, Invoice as _Invoice, Job as _Job, Service as _Service, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, Visit as _Visit, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAddress(arg0: Address): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAddress(to_candid_Address_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAddress(to_candid_Address_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addCustomer(arg0: Customer): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomer(to_candid_Customer_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomer(to_candid_Customer_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addExpense(arg0: Expense): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpense(to_candid_Expense_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpense(to_candid_Expense_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addInvoice(arg0: Invoice): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addInvoice(to_candid_Invoice_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInvoice(to_candid_Invoice_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addJob(arg0: Job): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addJob(to_candid_Job_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJob(to_candid_Job_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addService(arg0: Service): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addService(to_candid_Service_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addService(to_candid_Service_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addVisit(arg0: Visit): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addVisit(to_candid_Visit_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVisit(to_candid_Visit_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n22(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n22(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteExpense(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpense(arg0);
            return result;
        }
    }
    async getActiveAddressesByCustomer(arg0: string): Promise<Array<Address>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveAddressesByCustomer(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveAddressesByCustomer(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAddress(arg0: string): Promise<Address | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAddress(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAddress(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomer(arg0: string): Promise<Customer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInvoicesByCustomer(arg0: string): Promise<Array<Invoice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoicesByCustomer(arg0);
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoicesByCustomer(arg0);
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJob(arg0: string): Promise<Job | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJob(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJob(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobServices(arg0: string): Promise<Array<Service>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobServices(arg0);
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobServices(arg0);
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobsByAddress(arg0: string): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobsByAddress(arg0);
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobsByAddress(arg0);
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettings(): Promise<Settings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVisit(arg0: string): Promise<Visit | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisit(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisit(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listActiveCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.listActiveCustomers();
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listActiveCustomers();
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAddressesByCustomer(arg0: string): Promise<Array<Address>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAddressesByCustomer(arg0);
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAddressesByCustomer(arg0);
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllExpenses(): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllExpenses();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllExpenses();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async listExpensesByJob(arg0: string): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.listExpensesByJob(arg0);
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listExpensesByJob(arg0);
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async listExpensesByVisit(arg0: string): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.listExpensesByVisit(arg0);
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listExpensesByVisit(arg0);
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async listVisitsByJob(arg0: string): Promise<Array<Visit>> {
        if (this.processError) {
            try {
                const result = await this.actor.listVisitsByJob(arg0);
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listVisitsByJob(arg0);
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async loadSeedData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.loadSeedData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loadSeedData();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateExpense(arg0: Expense): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExpense(to_candid_Expense_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExpense(to_candid_Expense_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateJob(arg0: Job): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJob(to_candid_Job_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJob(to_candid_Job_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateSettings(arg0: Settings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSettings(arg0);
            return result;
        }
    }
    async updateVisit(arg0: Visit): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVisit(to_candid_Visit_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVisit(to_candid_Visit_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Address_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Address): Address {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Customer_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Customer): Customer {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Expense_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Expense): Expense {
    return from_candid_record_n52(_uploadFile, _downloadFile, value);
}
function from_candid_Invoice_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Invoice): Invoice {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Job_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Job): Job {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Service_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Service): Service {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Visit_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Visit): Visit {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Address]): Address | null {
    return value.length === 0 ? null : from_candid_Address_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Customer]): Customer | null {
    return value.length === 0 ? null : from_candid_Customer_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Job]): Job | null {
    return value.length === 0 ? null : from_candid_Job_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Visit]): Visit | null {
    return value.length === 0 ? null : from_candid_Visit_n46(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    street: string;
    country: string;
    city: string;
    postalCode: string;
    state: string;
    isPrimary: boolean;
    addressLabel: string;
    notes: [] | [string];
    customerId: string;
}): {
    id: string;
    street: string;
    country: string;
    city: string;
    postalCode: string;
    state: string;
    isPrimary: boolean;
    addressLabel: string;
    notes?: string;
    customerId: string;
} {
    return {
        id: value.id,
        street: value.street,
        country: value.country,
        city: value.city,
        postalCode: value.postalCode,
        state: value.state,
        isPrimary: value.isPrimary,
        addressLabel: value.addressLabel,
        notes: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.notes)),
        customerId: value.customerId
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    tags: Array<string>;
    isActive: boolean;
    email: string;
    notes: [] | [string];
    phone: string;
}): {
    id: string;
    name: string;
    tags: Array<string>;
    isActive: boolean;
    email: string;
    notes?: string;
    phone: string;
} {
    return {
        id: value.id,
        name: value.name,
        tags: value.tags,
        isActive: value.isActive,
        email: value.email,
        notes: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.notes)),
        phone: value.phone
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    dateIssued: _Time;
    dueDate: _Time;
    timeEntryIds: Array<string>;
    jobIds: Array<string>;
    materialEntryIds: Array<string>;
    totalAmount: number;
    notes: [] | [string];
    timeBlockIds: Array<string>;
    customerId: string;
}): {
    id: string;
    status: string;
    dateIssued: Time;
    dueDate: Time;
    timeEntryIds: Array<string>;
    jobIds: Array<string>;
    materialEntryIds: Array<string>;
    totalAmount: number;
    notes?: string;
    timeBlockIds: Array<string>;
    customerId: string;
} {
    return {
        id: value.id,
        status: value.status,
        dateIssued: value.dateIssued,
        dueDate: value.dueDate,
        timeEntryIds: value.timeEntryIds,
        jobIds: value.jobIds,
        materialEntryIds: value.materialEntryIds,
        totalAmount: value.totalAmount,
        notes: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.notes)),
        timeBlockIds: value.timeBlockIds,
        customerId: value.customerId
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    startTime: _Time;
    status: string;
    endTime: _Time;
    cost: number;
    isActive: boolean;
    addressId: string;
    notes: [] | [string];
    customerId: string;
    serviceId: string;
}): {
    id: string;
    startTime: Time;
    status: string;
    endTime: Time;
    cost: number;
    isActive: boolean;
    addressId: string;
    notes?: string;
    customerId: string;
    serviceId: string;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        status: value.status,
        endTime: value.endTime,
        cost: value.cost,
        isActive: value.isActive,
        addressId: value.addressId,
        notes: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.notes)),
        customerId: value.customerId,
        serviceId: value.serviceId
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    description: string;
    isActive: boolean;
    notes: [] | [string];
    price: number;
    laborRate: number;
}): {
    id: string;
    name: string;
    description: string;
    isActive: boolean;
    notes?: string;
    price: number;
    laborRate: number;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        isActive: value.isActive,
        notes: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.notes)),
        price: value.price,
        laborRate: value.laborRate
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    startTime: [] | [_Time];
    status: string;
    endTime: [] | [_Time];
    scheduledDate: _Time;
    createdAt: _Time;
    laborHours: number;
    jobId: string;
    photoIds: Array<string>;
    updatedAt: _Time;
    notes: [] | [string];
    internalNotes: [] | [string];
    laborCost: number;
    laborRate: number;
}): {
    id: string;
    startTime?: Time;
    status: string;
    endTime?: Time;
    scheduledDate: Time;
    createdAt: Time;
    laborHours: number;
    jobId: string;
    photoIds: Array<string>;
    updatedAt: Time;
    notes?: string;
    internalNotes?: string;
    laborCost: number;
    laborRate: number;
} {
    return {
        id: value.id,
        startTime: record_opt_to_undefined(from_candid_opt_n48(_uploadFile, _downloadFile, value.startTime)),
        status: value.status,
        endTime: record_opt_to_undefined(from_candid_opt_n48(_uploadFile, _downloadFile, value.endTime)),
        scheduledDate: value.scheduledDate,
        createdAt: value.createdAt,
        laborHours: value.laborHours,
        jobId: value.jobId,
        photoIds: value.photoIds,
        updatedAt: value.updatedAt,
        notes: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.notes)),
        internalNotes: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.internalNotes)),
        laborCost: value.laborCost,
        laborRate: value.laborRate
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    expenseType: string;
    dateIncurred: _Time;
    jobId: [] | [string];
    description: string;
    notes: [] | [string];
    visitId: [] | [string];
    amount: number;
    vendorName: [] | [string];
    receiptBlobId: [] | [string];
}): {
    id: string;
    expenseType: string;
    dateIncurred: Time;
    jobId?: string;
    description: string;
    notes?: string;
    visitId?: string;
    amount: number;
    vendorName?: string;
    receiptBlobId?: string;
} {
    return {
        id: value.id,
        expenseType: value.expenseType,
        dateIncurred: value.dateIncurred,
        jobId: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.jobId)),
        description: value.description,
        notes: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.notes)),
        visitId: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.visitId)),
        amount: value.amount,
        vendorName: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.vendorName)),
        receiptBlobId: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.receiptBlobId))
    };
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Address>): Array<Address> {
    return value.map((x)=>from_candid_Address_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Invoice>): Array<Invoice> {
    return value.map((x)=>from_candid_Invoice_n36(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Service>): Array<Service> {
    return value.map((x)=>from_candid_Service_n42(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Job>): Array<Job> {
    return value.map((x)=>from_candid_Job_n39(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Customer>): Array<Customer> {
    return value.map((x)=>from_candid_Customer_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Expense>): Array<Expense> {
    return value.map((x)=>from_candid_Expense_n51(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Visit>): Array<Visit> {
    return value.map((x)=>from_candid_Visit_n46(_uploadFile, _downloadFile, x));
}
function to_candid_Address_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Address): _Address {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_Customer_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Customer): _Customer {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Expense_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Expense): _Expense {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_Invoice_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Invoice): _Invoice {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_Job_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Job): _Job {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_Service_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Service): _Service {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_Visit_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Visit): _Visit {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    tags: Array<string>;
    isActive: boolean;
    email: string;
    notes?: string;
    phone: string;
}): {
    id: string;
    name: string;
    tags: Array<string>;
    isActive: boolean;
    email: string;
    notes: [] | [string];
    phone: string;
} {
    return {
        id: value.id,
        name: value.name,
        tags: value.tags,
        isActive: value.isActive,
        email: value.email,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        phone: value.phone
    };
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    expenseType: string;
    dateIncurred: Time;
    jobId?: string;
    description: string;
    notes?: string;
    visitId?: string;
    amount: number;
    vendorName?: string;
    receiptBlobId?: string;
}): {
    id: string;
    expenseType: string;
    dateIncurred: _Time;
    jobId: [] | [string];
    description: string;
    notes: [] | [string];
    visitId: [] | [string];
    amount: number;
    vendorName: [] | [string];
    receiptBlobId: [] | [string];
} {
    return {
        id: value.id,
        expenseType: value.expenseType,
        dateIncurred: value.dateIncurred,
        jobId: value.jobId ? candid_some(value.jobId) : candid_none(),
        description: value.description,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        visitId: value.visitId ? candid_some(value.visitId) : candid_none(),
        amount: value.amount,
        vendorName: value.vendorName ? candid_some(value.vendorName) : candid_none(),
        receiptBlobId: value.receiptBlobId ? candid_some(value.receiptBlobId) : candid_none()
    };
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: string;
    dateIssued: Time;
    dueDate: Time;
    timeEntryIds: Array<string>;
    jobIds: Array<string>;
    materialEntryIds: Array<string>;
    totalAmount: number;
    notes?: string;
    timeBlockIds: Array<string>;
    customerId: string;
}): {
    id: string;
    status: string;
    dateIssued: _Time;
    dueDate: _Time;
    timeEntryIds: Array<string>;
    jobIds: Array<string>;
    materialEntryIds: Array<string>;
    totalAmount: number;
    notes: [] | [string];
    timeBlockIds: Array<string>;
    customerId: string;
} {
    return {
        id: value.id,
        status: value.status,
        dateIssued: value.dateIssued,
        dueDate: value.dueDate,
        timeEntryIds: value.timeEntryIds,
        jobIds: value.jobIds,
        materialEntryIds: value.materialEntryIds,
        totalAmount: value.totalAmount,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        timeBlockIds: value.timeBlockIds,
        customerId: value.customerId
    };
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    startTime: Time;
    status: string;
    endTime: Time;
    cost: number;
    isActive: boolean;
    addressId: string;
    notes?: string;
    customerId: string;
    serviceId: string;
}): {
    id: string;
    startTime: _Time;
    status: string;
    endTime: _Time;
    cost: number;
    isActive: boolean;
    addressId: string;
    notes: [] | [string];
    customerId: string;
    serviceId: string;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        status: value.status,
        endTime: value.endTime,
        cost: value.cost,
        isActive: value.isActive,
        addressId: value.addressId,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        customerId: value.customerId,
        serviceId: value.serviceId
    };
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    description: string;
    isActive: boolean;
    notes?: string;
    price: number;
    laborRate: number;
}): {
    id: string;
    name: string;
    description: string;
    isActive: boolean;
    notes: [] | [string];
    price: number;
    laborRate: number;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        isActive: value.isActive,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        price: value.price,
        laborRate: value.laborRate
    };
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    startTime?: Time;
    status: string;
    endTime?: Time;
    scheduledDate: Time;
    createdAt: Time;
    laborHours: number;
    jobId: string;
    photoIds: Array<string>;
    updatedAt: Time;
    notes?: string;
    internalNotes?: string;
    laborCost: number;
    laborRate: number;
}): {
    id: string;
    startTime: [] | [_Time];
    status: string;
    endTime: [] | [_Time];
    scheduledDate: _Time;
    createdAt: _Time;
    laborHours: number;
    jobId: string;
    photoIds: Array<string>;
    updatedAt: _Time;
    notes: [] | [string];
    internalNotes: [] | [string];
    laborCost: number;
    laborRate: number;
} {
    return {
        id: value.id,
        startTime: value.startTime ? candid_some(value.startTime) : candid_none(),
        status: value.status,
        endTime: value.endTime ? candid_some(value.endTime) : candid_none(),
        scheduledDate: value.scheduledDate,
        createdAt: value.createdAt,
        laborHours: value.laborHours,
        jobId: value.jobId,
        photoIds: value.photoIds,
        updatedAt: value.updatedAt,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        internalNotes: value.internalNotes ? candid_some(value.internalNotes) : candid_none(),
        laborCost: value.laborCost,
        laborRate: value.laborRate
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    street: string;
    country: string;
    city: string;
    postalCode: string;
    state: string;
    isPrimary: boolean;
    addressLabel: string;
    notes?: string;
    customerId: string;
}): {
    id: string;
    street: string;
    country: string;
    city: string;
    postalCode: string;
    state: string;
    isPrimary: boolean;
    addressLabel: string;
    notes: [] | [string];
    customerId: string;
} {
    return {
        id: value.id,
        street: value.street,
        country: value.country,
        city: value.city,
        postalCode: value.postalCode,
        state: value.state,
        isPrimary: value.isPrimary,
        addressLabel: value.addressLabel,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        customerId: value.customerId
    };
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
